### ISSUE TITLE
Boxbot.prototype.exec 的返回类型问题

### ISSUE THREAD

**Issue by hardfist** [qiuxiang/boxbot#2]
十分喜欢你的程序，学习到了很多知识。
Boxbot.prototyp.exec的返回值是promise或者false，而对exec的调用结果却未进行类型检查。虽然可以看出程序中的exec总是返回promise，但是似乎有些隐晦，是否可以考虑将exec的返回类型统一为promise，比如当command为false时，返回promise.reject('command not supported')。

**Comment by qiuxiang** [comment]
感谢你的关注。

有考虑过统一返回 promise，但要多做一些工作。为了区分**运行失败**和**解析失败**这两种情况，需要定义两种异常 ExecError 和 ParseError，对应的，运行失败时要写成 throw new ExecError('...')，解析失败要写成 promise.reject(new ParseError('command not found'))。进一步想，将来要实现命令错误提示，比如提示某个参数错误、命令拼写错误，这种做法就更有必要了。

但回过头，我是觉得现在没有必要啦，因为 exec 同时也用于检测命令是否正确，返回 false 某种程度上更直观，JSDoc 也写得很明白了 `@returns {boolean|Promise}`。
